[package]
name = "ssb-validate2-rsjs-wasm"
version = "0.1.0"
authors = ["Andrew Reid <glyph@mycelial.technology>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-rayon = { version = "1.0", features = ["no-bundler"] }
ssb-validate = { git = "https://github.com/mycognosist/ssb-validate" }
ssb-verify-signatures = "1.0.0"
