[package]
name = "ssb-validate2-rsjs-wasm"
version = "0.5.0"
authors = ["Andrew Reid <glyph@mycelial.technology>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ssb-validate = { git = "https://github.com/sunrise-choir/ssb-validate" }
ssb-verify-signatures = { git = "https://github.com/sunrise-choir/ssb-verify-signatures" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-rayon = "1.0"
